package com.example.allcollections.feature.collection.components

val PRESET_CATEGORIES = listOf(
    "Accendini",
    "Action Figure & Funko",
    "Adesivi & Sticker",
    "Arte & Fotografia",
    "Autografi",
    "Biglietti & Ticket (Eventi)",
    "Borse & Accessori Lusso",
    "Boule de Neige",
    "Calamite & Souvenir",
    "Carte Collezionabili (TCG)",
    "Cartoline",
    "Cinema (Poster & Locandine)",
    "Console Vintage",
    "Design & Modernariato",
    "Documenti Storici",
    "Film (DVD, Blu-ray, VHS)",
    "Francobolli (Filatelia)",
    "Fumetti & Manga",
    "Giocattoli Vintage",
    "Gioielli & Bijoux",
    "Giochi da Tavolo & Ruolo",
    "LEGO & Mattoncini",
    "Libri & Riviste",
    "Macchinine (Die-cast)",
    "Memorabilia Sportiva",
    "Militaria (Medaglie & Uniformi)",
    "Modellismo (Treni, Aerei, Navi)",
    "Monete & Banconote (Numismatica)",
    "Orologi",
    "Patch & Toppe",
    "Penne Stilografiche",
    "Pietre, Fossili & Minerali",
    "Profumi & Mignonnette",
    "Scatole di Latta",
    "Sneakers & Streetwear",
    "Sorpresine & Gadget",
    "Spille & Pin",
    "Strumenti Musicali",
    "Tappi & Lattine",
    "Tazzine & Mug",
    "Tecnologia Vintage (PC, Macchine da scrivere)",
    "Thun & Ceramiche",
    "Videogiochi",
    "Vini & Distillati",
    "Vinili, CD & Cassette",
    "Altro ✏️"
)