package com.example.allcollections.feature.collection.components

val PRESET_CATEGORIES = listOf(
    "Fumetti & Manga",
    "Carte Collezionabili (TCG)",
    "Videogiochi",
    "Console & Hardware Vintage",
    "Action Figure & Statue",
    "LEGO & Mattoncini",
    "Giochi da Tavolo & Ruolo",
    "Modellismo (Auto, Treni, Navi)",
    "Die-Cast (Macchinine)",
    "Vinili, CD & Cassette",
    "Strumenti Musicali",
    "Cinema (Poster & Locandine)",
    "Autografi & Script",
    "Arte (Quadri & Sculture)",
    "Fotografia (Stampe & Macchine)",
    "Libri rari & Prime edizioni",
    "Numismatica (Monete & Banconote)",
    "Filatelia (Francobolli)",
    "Militaria (Medaglie & Uniformi)",
    "Documenti Storici",
    "Orologi",
    "Sneakers & Streetwear",
    "Borse & Accessori di Lusso",
    "Penne Stilografiche",
    "Accendini & Oggetti da fumo",
    "Gioielli & Bijoux Vintage",
    "Vini & Distillati Pregiati",
    "Memorabilia Sportiva",
    "Cimeli del Design (Modernariato)",
    "Tecnologia Vintage (PC, Macchine da scrivere)",
    "Giocattoli Vintage",
    "Altro ✏️"
)